# Generated by Django 5.0.2 on 2025-07-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('data_context', models.CharField(max_length=10000)),
                ('data_url', models.CharField(max_length=10000)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-date_from'],
            },
        ),
    ]
