# AnalyDocs/.github/workflows/firebase-hosting.yml
name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - master
    paths:
      - '/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (frontend)
        run: npm install
        working-directory: frontend

      - name: Build Next.js app
        run: npm run build
        working-directory: frontend

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANALYDOCS }}'
          projectId: analydocs-test
          channelId: live
          entryPoint: frontend/ # This correctly points to your firebase.json
          # --- REVERTED CHANGE STARTS HERE ---
          target: frontend # Put this line back! It's the correct way to specify the target for this action
          # Removed: args: '--only hosting:frontend'
          # --- REVERTED CHANGE ENDS HERE ---