# AnalyDocs/.github/workflows/firebase-hosting.yml
name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (frontend)
        run: npm install
        working-directory: frontend

      - name: Build Next.js app
        run: npm run build
        working-directory: frontend

      # --- ADD THIS NEW DIAGNOSTIC STEP HERE ---
      - name: List 'out' directory contents
        run: |
          echo "Listing contents of frontend/out/:"
          ls -F frontend/out/ # Using -F to indicate directories with /
          echo "Listing all contents recursively in frontend/out/:"
          ls -R frontend/out/ # Recursive list for full detail
      # --- END OF NEW DIAGNOSTIC STEP ---

      - name: Manual Firebase CLI Deployment
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANALYDOCS }}'
        run: |
          echo "Installing firebase-tools@12.9.0 globally..."
          npm install -g firebase-tools@12.9.0
          # ... (rest of your deployment script) ...