# AnalyDocs/.github/workflows/firebase-hosting.yml
name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (frontend)
        run: npm install
        working-directory: frontend

      - name: Build Next.js app
        run: npm run build
        working-directory: frontend

      - name: Manual Firebase CLI Deployment
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANALYDOCS }}
        run: |
          echo "Installing firebase-tools@12.9.0 globally..."
          npm install -g firebase-tools@12.9.0

          # Diagnostic lines (keep for now to confirm behavior)
          echo "Verifying firebase CLI path..."
          which firebase || command -v firebase || type firebase
          echo "Verifying firebase CLI version..."
          firebase --version

          echo "Authenticating Firebase CLI using GOOGLE_APPLICATION_CREDENTIALS..."
          # 1. Write the service account key to a temporary file
          #    Using /tmp/ for temporary files on Linux runners
          echo "${FIREBASE_SERVICE_ACCOUNT_KEY}" > /tmp/service_account_key.json

          # 2. Set the GOOGLE_APPLICATION_CREDENTIALS environment variable.
          #    This is the standard way for Google Cloud client libraries (like Firebase CLI)
          #    to automatically find service account credentials.
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/service_account_key.json"

          # No need for 'firebase login' or 'gcloud auth' as GOOGLE_APPLICATION_CREDENTIALS handles it

          echo "Changing directory to frontend/"
          cd frontend

          echo "Deploying frontend to Firebase Hosting..."
          # We can remove --project here as it should be picked up by .firebaserc default project
          # and the GOOGLE_APPLICATION_CREDENTIALS set for the correct project.
          firebase deploy --only hosting:frontend 

          # Clean up the temporary file immediately after deployment for security
          rm /tmp/service_account_key.json