# AnalyDocs/.github/workflows/firebase-hosting.yml
name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (frontend)
        run: npm install
        working-directory: frontend

      - name: Build Next.js app
        run: npm run build
        working-directory: frontend

      - name: Manual Firebase CLI Deployment
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANALYDOCS }}
        run: |
          echo "Installing firebase-tools@12.9.0 globally..."
          npm install -g firebase-tools@12.9.0

          # --- ADD THESE DIAGNOSTIC LINES ---
          echo "Verifying firebase CLI path..."
          which firebase || command -v firebase || type firebase # Try multiple ways to find the executable path
          echo "Verifying firebase CLI version..."
          firebase --version # This should show 12.9.0
          # --- END DIAGNOSTIC LINES ---

          echo "Authenticating Firebase CLI..."
          echo "${FIREBASE_SERVICE_ACCOUNT_KEY}" > service_account_key.json
          firebase login --service-account --project analydocs-test < service_account_key.json
          rm service_account_key.json # Clean up the temporary file

          echo "Changing directory to frontend/"
          cd frontend

          echo "Deploying frontend to Firebase Hosting..."
          firebase deploy --only hosting:frontend --project analydocs-test